### ISSUE TITLE
Replacing _'s with .'s

### ISSUE THREAD

**Issue by ThomasCat** [Ray1235/SourceMayaTools#4]
Why have you explicitly made it so that every time a _ shows up you replace it with a . upon export. I don't see a logical reason for this, and frankly its a bit retarded. Maybe try fix it in your spare time as it is only a line of code. Hopefully you can fit this in between taking photos for twitter :)

**Comment by TheEnbyWitch** [comment]
This was done because when importing SMDs (with MESA for example) the first `.` was replaced with a `_`, because Maya doesn't support having `.` in names. This was done in order not to break those imports.

If you want to change it, feel free to change the True to False on this line
https://github.com/LunaRyuko/SourceMayaTools/blob/master/SourceMayaTools.py#L31
